name: Configure Conan Repository
description: Configure the correct Artifactory server

runs:
  using: "composite"
  steps:
    - name: Use production repository
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/alternative-structure' }}
      run: |
        echo "----> Using production server"
        conan remote add peak8 https://dandresky.jfrog.io/artifactory/api/conan/peak8
        conan user "$CONAN_USERNAME" -r peak8 -p "$CONAN_PASSWORD"
        conan profile update settings.compiler.libcxx=libstdc++11 default
      shell: bash
