name: Build Libraries for Mac ARMv8
on:
  workflow_call:
    inputs:
      options:
        description: 'A string of any options for the package'
        required: false
        type: string
        default: ''
    secrets:
      CONAN_USERNAME:
        required: true
      CONAN_PASSWORD:
        required: true

env:
  CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_NON_INTERACTIVE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_LOGGING_LEVEL: debug

jobs:
  mac_intel_job:
    name: Build Mac ARMv8 Libraries
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Conan
        run: brew install conan

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Build zlib
        id: zlib-1_2_13
        uses: ./.github/actions/conan-create
        with:
          package_name: zlib
          package_version: 1.2.13
          profile_build: default
          profile_host: conan-profiles/mac-armv8
          recipe_directory: 'recipes/zlib/1.2.13'
          os: Macos
          arch: armv8
      