name: Build Libraries for MacOS and iOS
on:
  workflow_call:
    inputs:
      options:
        description: 'A string of any options for the package'
        required: false
        type: string
        default: ''
    secrets:
      CONAN_USERNAME:
        required: true
      CONAN_PASSWORD:
        required: true

env:
  CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_NON_INTERACTIVE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_LOGGING_LEVEL: debug

jobs:
  mac_ios_job:
    name: Build Libraries for MacOS and iOS
    runs-on: macos-12
    strategy:
      matrix:
        host_profile: [mac-x86_64, mac-armv8]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Conan
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          pip install conan==1.58

      # - name: Install Conan
      #   run: |
      #     brew tap-new $USER/local-conan
      #     brew extract --version=1.58 conan $USER/local-conan
      #     brew install $USER/local-conan/conan@1.58

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Build zlib
        id: zlib-1_2_13
        uses: ./.github/actions/conan-create
        with:
          package_name: zlib
          package_version: 1.2.13
          profile_build: default
          profile_host: conan-profiles/${{ matrix.host_profile }}
          recipe_directory: 'recipes/zlib/1.2.13'
          build_type: ${{ matrix.build_type }}
      