name: Build Libraries for Windows x86_64
on:
  workflow_call:
    inputs:
      options:
        description: 'A string of any options for the package'
        required: false
        type: string
        default: ''
    secrets:
      CONAN_USERNAME:
        required: true
      CONAN_PASSWORD:
        required: true

env:
  CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_NON_INTERACTIVE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_LOGGING_LEVEL: debug

jobs:
  windows_job:
    name: Build Windows Libraries
    runs-on: windows-2019
    strategy:
      matrix:
        host_profile: [windows-x86_64]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3.3.0

      # SPECIFY TOOLSET IN THE PROFILE INSTEAD OF INSTALLING 2017
      # - name: Install Visual Studio 2017
      #   run: |
      #     choco install visualstudio2017community
      #     choco install visualstudio2017-workload-universal --package-parameters "--includeOptional"
      #     choco install visualstudio2017-workload-vctools --package-parameters "--includeOptional"

      - name: Install Conan
        run: pip install conan==1.58

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Build zlib
        id: zlib-1_2_13
        uses: ./.github/actions/conan-create
        with:
          package_name: zlib
          package_version: 1.2.13
          profile_build: default
          profile_host: conan-profiles/${{ matrix.host_profile }}
          recipe_directory: 'recipes/zlib/1.2.13'
          build_type: ${{ matrix.build_type }}
      