name: Build Libraries for Linux ARMv8
on:
  workflow_call:
    inputs:
      options:
        description: 'A string of any options for the package'
        required: false
        type: string
        default: ''
    secrets:
      CONAN_USERNAME:
        required: true
      CONAN_PASSWORD:
        required: true

env:
  CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_NON_INTERACTIVE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_LOGGING_LEVEL: debug

jobs:
  linux_armv8_job:
    # Builds libraries for use in applications to be deployed in the Linux armv8 machine like the Verdin iMX8M+
    name: Build Linux Libraries
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Install Conan
        run: pip install --force-reinstall conan==1.58

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Build zlib
        id: zlib-1_2_13
        uses: ./.github/actions/conan-create
        with:
          package_name: zlib
          package_version: 1.2.13
          profile_build: conan-profiles/linux-armv8-build
          profile_host: conan-profiles/linux-armv8-host
          recipe_directory: 'recipes/zlib/1.2.13'
          build_type: ${{ matrix.build_type }}
          os: Linux
          arch: armv8
      