# This is the main workflow for the conan-cross-compile project. At this level we launch workflows based on
# target platform or project. 

name: Main Workflow

on:
  push:
    branches: 
      - 'main'
      - 'alternative-structure'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  what-to-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        manifest: 
          - linux-x86_64.json
          - linux-armv8.json
    secrets:
      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Conan
        run: pip install conan

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Install JSON Parser
        run: sudo apt install jq

      - name: Download all Conan package metadata
        id: download-all-conan-package-metadata
        shell: bash
        run: conan search -r peak8 --json search-conan-all.json
      
      - name: Read manifest
        id: read-manifest
        shell: bash
        run: |
          export MANIFEST=$(jq .libraries[] manifests/${{ matrix.manifest }})
          echo "manifest=\"${MANIFEST}\"" >> $GITHUB_OUTPUT



  # libraries-for-linux-x86_64:
  #   uses: peak8/conan-cross-compile/.github/workflows/build-libraries-for-linux-x86_64.yml@alternative-structure
  #   secrets:
  #     CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  #     CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}










  # zlib:
  #   uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
  #   with:
  #     package_name: zlib
  #     package_version: 1.2.13
  #     recipe_directory: 'recipes/zlib/1.2.13'
  #   secrets:
  #     CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  #     CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
#  boost:
#    uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
#    with:
#      package_name: boost
#      package_version: 1.78.0
#      recipe_directory: 'recipes/boost/all'
#      options: '-o boost:without_locale=True'
#    secrets:
#      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
#      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
#  protobuf:
#    uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
#    with:
#      package_name: protobuf
#      package_version: 3.12.4
#      recipe_directory: 'recipes/protobuf/all'
#      options: '-o zeromq:shared=True'
#    secrets:
#      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
#      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
#  cli11:
#    uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
#    with:
#      package_name: cli11
#     package_version: 1.9.1
#      recipe_directory: 'recipes/cli11/all'
#    secrets:
#      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
#      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
#  poco:
#    uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
#    if: ${{ false }}
#    with:
#      package_name: poco
#      package_version: 1.10.1
#      recipe_directory: 'recipes/poco/all'
#      options: '-o poco:enable_crypto=False -o poco:enable_data_mysql=False -o poco:enable_data_postgresql=False -o poco:enable_data_sqlite=False -o poco:enable_jwt=False -o poco:enable_mongodb=False -o poco:enable_net=False -o poco:enable_netssl=False -o poco:enable_redis=False'
#   secrets:
#      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
#      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
#  libusb:
#    uses: peak8/conan-cross-compile/.github/workflows/build-conan-package.yml@main
#    with:
#      package_name: libusb
#      package_version: 1.0.24
#      recipe_directory: 'recipes/libusb/all'
#    secrets:
#      CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
#      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

  