name: Search Conan repository for all libraries identified in the manifest files
on:
  workflow_call:
    secrets:
      CONAN_USERNAME:
        required: true
      CONAN_PASSWORD:
        required: true

env:
  CONAN_USERNAME: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_NON_INTERACTIVE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_LOGGING_LEVEL: debug

jobs:

  search-conan-manifest:
    name: Search Conan remote for packages aligning with manifest files
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Conan
        run: pip install conan

      - name: Configure Conan
        uses: ./.github/actions/configure-conan

      - name: Install JSON Parser
        run: sudo apt install jq

      - name: Build zlib
        id: zlib-1_2_13
        uses: ./.github/actions/conan-create
        with:
          package_name: zlib
          package_version: 1.2.13
          conan-profile: conan-profiles/linux-x86_64
          conan-recipe: 'recipes/zlib/1.2.13'
      